dist: xenial

services:
  - postgresql
matrix:
  include:
    - addons:
      postgresql: "9.4"
    - addons:
      postgresql: "9.6"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
  - "3.8" 
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - ./manage.py test authentication
  - ./manage.py test census
